### ISSUE TITLE
500 Internal Server Error on pushjet.io

### ISSUE THREAD

**Issue by AJOnlineServices** [Pushjet/Pushjet-Android#29] opened 2018-02-28 18:19 UTC
I have suddenly stopped receiving notifications.
When checking on the docs.pushjet.io pages, I have tried to create a new service and send a test message.

All works perfectly, and i get a HTTP 200 response.

As soon as I open the PushJet app on my phone and subscribe to the service, any subsequent messages sent result in a HTTP 500 error.

![36804911-dc7d335e-1cb3-11e8-96c5-07a137d59c00](https://user-images.githubusercontent.com/1144171/36894643-fb617c02-1e03-11e8-8bfa-7d76781292c4.png)

**Comment by macau23** [comment] 2018-03-02 10:17
@AJOnlineServices your secret is public

**Comment by Mechazawa** [comment] 2018-03-02 10:25
I've removed removed the secret from the image

**Comment by Mechazawa** [comment] 2018-03-02 10:27
I don't seem to have any issues sending messages. I can't test receiving them in the app because I don't own an Android phone anymore.

**Comment by AJOnlineServices** [comment] 2018-03-02 12:58
I left the secret visible so the error could be reproduced if needed - the secret was for a test service which I created just as I made the original post - it's not being used for anything.

I have made another service and as soon as I register my device to subscribe to it, I get HTTP 500 errors again when sending any message.

**Comment by AJOnlineServices** [comment] 2018-03-02 22:32
I've just realised that I've posted this in the Android section instead of the Server section :/

**Comment by AJOnlineServices** [comment] 2018-03-08 20:26
Any update on this issue? It is still happening on all devices that I have tested, as well as the PushJet test site when sedning messages directly from that page.

**Comment by adamnovak** [comment] 2018-03-15 23:44
I can replicate this as well. I think #30 is a duplicate of this issue.

I have an Android device subscribed and every notification I send gives a 500. The device is not notified. Doing a pull-to-refresh in the Android app causes the notifications to appear in the app (not as notifications but as entries in the list of past notifications).

**Comment by Mechazawa** [comment] 2018-03-16 11:16
Sorry about that, I don't have the time to maintain this project anymore and it kinda slipped through the cracks. I've fixed the issue. It had to do with a misconfigured server with some outdated packages that were causing issues. 

It should be fixed. I'll close this issue, please remake one when this happens again.

**Closed as completed by Mechazawa** 2018-03-16 11:16 UTC
